<?php

namespace Database\Seeders;

use App\Models\Preset;
use Illuminate\Database\Seeder;

class PresetSeeder extends Seeder
{
    /**
     * Seed the presets table with v0.32 device flow step presets.
     *
     * These presets represent reusable command sequences for chemical
     * analysis device operations (ADC controller via MQTT).
     */
    public function run(): void
    {
        $presets = [
            // ─── Initialization Presets ───────────────────────────
            [
                'name' => 'System Initialize',
                'description' => 'Initialize all device controllers to default state. Run this before any protocol execution.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'pump_0',
                        'action' => 'init',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 2,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'pump_0',
                        'action' => 'home',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 1,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'pump_1',
                        'action' => 'init',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 2,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'pump_1',
                        'action' => 'home',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 1,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'rotary_valve_1',
                        'action' => 'init',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 2,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'rotary_valve_1',
                        'action' => 'home',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 1,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'rotary_valve_2',
                        'action' => 'init',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 2,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'rotary_valve_2',
                        'action' => 'home',
                        'value' => '',
                        'type' => 'none',
                        'delay' => 3,
                        'retry_count' => 1,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'stop',
                        'value' => 'stop',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'tec',
                        'action' => 'setpoint',
                        'value' => 25.0,
                        'type' => 'float',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                ],
            ],

            // ─── Temperature Control Presets ─────────────────────
            [
                'name' => 'Heat to 37°C',
                'description' => 'Set TEC controller to 37°C for incubation. Includes stirrer at low speed for even heating.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'tec',
                        'action' => 'enable',
                        'value' => 1,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 15,
                    ],
                    [
                        'controller' => 'tec',
                        'action' => 'setpoint',
                        'value' => 37.0,
                        'type' => 'float',
                        'delay' => 5,
                        'retry_count' => 1,
                        'timeout' => 30,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 200,
                        'type' => 'int',
                        'delay' => 3,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                ],
            ],

            [
                'name' => 'Cool to 4°C',
                'description' => 'Rapid cool-down to 4°C for sample preservation. Stops stirrer after reaching target.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'tec',
                        'action' => 'enable',
                        'value' => 1,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 15,
                    ],
                    [
                        'controller' => 'tec',
                        'action' => 'setpoint',
                        'value' => 4.0,
                        'type' => 'float',
                        'delay' => 5,
                        'retry_count' => 2,
                        'timeout' => 60,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 100,
                        'type' => 'int',
                        'delay' => 3,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                ],
            ],

            [
                'name' => 'TEC Disable',
                'description' => 'Disable TEC controller and return to ambient temperature.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'tec',
                        'action' => 'enable',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            // ─── Fluid Handling Presets ──────────────────────────
            [
                'name' => 'Aspirate Sample (100µL)',
                'description' => 'Aspirate 100µL of sample through the pump. Open valve before aspiration, close after.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'microvalve',
                        'action' => 'open',
                        'value' => 1,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'aspirate',
                        'value' => 100.0,
                        'type' => 'float',
                        'delay' => 8,
                        'retry_count' => 2,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            [
                'name' => 'Aspirate Sample (250µL)',
                'description' => 'Aspirate 250µL of sample. Standard volume for mAb analysis.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'microvalve',
                        'action' => 'open',
                        'value' => 1,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'aspirate',
                        'value' => 250.0,
                        'type' => 'float',
                        'delay' => 12,
                        'retry_count' => 2,
                        'timeout' => 60,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            [
                'name' => 'Dispense to Waste',
                'description' => 'Dispense full pump volume to waste container.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'waste',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'dispense',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            [
                'name' => 'Dispense to Collection',
                'description' => 'Dispense pump volume to sample collection vial.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'collect',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'dispense',
                        'value' => 250.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            // ─── Mixing Presets ──────────────────────────────────
            [
                'name' => 'Mix High Speed',
                'description' => 'Run stirrer at high speed (800 RPM) for vigorous mixing.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 800,
                        'type' => 'int',
                        'delay' => 3,
                        'retry_count' => 1,
                        'timeout' => 15,
                    ],
                ],
            ],

            [
                'name' => 'Mix Low Speed',
                'description' => 'Run stirrer at low speed (200 RPM) for gentle mixing during incubation.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 200,
                        'type' => 'int',
                        'delay' => 3,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                ],
            ],

            [
                'name' => 'Stop Stirrer',
                'description' => 'Stop the stirrer motor.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'stirrer',
                        'action' => 'stop',
                        'value' => 'stop',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            // ─── Wash Presets ────────────────────────────────────
            [
                'name' => 'Wash Cycle (3x)',
                'description' => 'Standard 3-cycle wash: aspirate wash buffer, mix, dispense to waste. For between-step cleaning.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    // Cycle 1
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'wash',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 1,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'aspirate',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 600,
                        'type' => 'int',
                        'delay' => 5,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'stop',
                        'value' => 'stop',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'waste',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'dispense',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    // Cycle 2
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'wash',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'aspirate',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 600,
                        'type' => 'int',
                        'delay' => 5,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'stop',
                        'value' => 'stop',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'waste',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'dispense',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    // Cycle 3
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'wash',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'aspirate',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 600,
                        'type' => 'int',
                        'delay' => 5,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'stop',
                        'value' => 'stop',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'set',
                        'value' => 'waste',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'dispense',
                        'value' => 500.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 1,
                        'timeout' => 45,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                ],
            ],

            // ─── Shutdown Preset ─────────────────────────────────
            [
                'name' => 'System Shutdown',
                'description' => 'Safe shutdown sequence. Stops all motors, closes valves, disables TEC, homes pump.',
                'version' => '0.32',
                'author' => 'System',
                'status' => 'Active',
                'commands' => [
                    [
                        'controller' => 'stirrer',
                        'action' => 'stop',
                        'value' => 'stop',
                        'type' => 'string',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'tec',
                        'action' => 'enable',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'microvalve',
                        'action' => 'close',
                        'value' => 0,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'pump',
                        'action' => 'home',
                        'value' => 'start',
                        'type' => 'string',
                        'delay' => 5,
                        'retry_count' => 1,
                        'timeout' => 30,
                    ],
                ],
            ],

            // ─── Draft Presets (for testing) ─────────────────────
            [
                'name' => 'Custom Temperature Ramp',
                'description' => 'Draft preset for testing temperature ramping from 25°C to 50°C with mixing.',
                'version' => '0.32',
                'author' => 'Admin PanCake',
                'status' => 'Draft',
                'commands' => [
                    [
                        'controller' => 'tec',
                        'action' => 'enable',
                        'value' => 1,
                        'type' => 'int',
                        'delay' => 2,
                        'retry_count' => 0,
                        'timeout' => 10,
                    ],
                    [
                        'controller' => 'tec',
                        'action' => 'setpoint',
                        'value' => 50.0,
                        'type' => 'float',
                        'delay' => 10,
                        'retry_count' => 2,
                        'timeout' => 120,
                    ],
                    [
                        'controller' => 'stirrer',
                        'action' => 'speed',
                        'value' => 400,
                        'type' => 'int',
                        'delay' => 3,
                        'retry_count' => 0,
                        'timeout' => 15,
                    ],
                ],
            ],
        ];

        foreach ($presets as $presetData) {
            Preset::updateOrCreate(
                ['name' => $presetData['name'], 'version' => $presetData['version']],
                $presetData
            );
        }
    }
}
